### ISSUE TITLE
Getting INTERNAL: No error: A GRPC status of OK should have been sent occasionaly

### ISSUE THREAD

**Issue by yshahak** [onflow/flow-jvm-sdk#9]
### Problem

Occasionally(i.e not for every call) I get this `Exception` when using the `sdk`:
(The code is run on `Android` device)
```
2021-05-14 10:21:35.827 29952-30028/com.flow.demo W/System.err: io.grpc.StatusRuntimeException: INTERNAL: No error: A GRPC status of OK should have been sent
2021-05-14 10:21:35.827 29952-30028/com.flow.demo W/System.err: Rst Stream
2021-05-14 10:21:35.828 29952-30028/com.flow.demo W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
2021-05-14 10:21:35.828 29952-30028/com.flow.demo W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
2021-05-14 10:21:35.829 29952-30028/com.flow.demo W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
2021-05-14 10:21:35.829 29952-30028/com.flow.demo W/System.err:     at org.onflow.protobuf.access.AccessAPIGrpc$AccessAPIBlockingStub.executeScriptAtLatestBlock(AccessAPIGrpc.java:1502)
```
This is happening when executing this lines:
```kotlin
override fun executeScriptAtLatestBlock(script: FlowScript, args: List<FlowArgument>): FlowScriptResponse {
        val ret = api.executeScriptAtLatestBlock(
            Access.ExecuteScriptAtLatestBlockRequest.newBuilder()
                .setScript(script.byteStringValue)
                .addAllArguments(args.map { it.byteStringValue })
                .build()
        )
        return FlowScriptResponse(ret.value.toByteArray())
    }
```

Wondered if anyone familiar with this `exception`? Googled it and didn't see anything seems to be related.

**Comment by yshahak** [comment]
Ok, after a lot of digging and playing around, I think I might found something.
If I replace the code 
```kotlin
var channelBuilder = ManagedChannelBuilder
            .forAddress(host, port)
            .userAgent(userAgent)
```
with 
```kotlin
var channelBuilder = OkHttpChannelBuilder
            .forAddress(host, port)
            .userAgent(userAgent)
            .flowControlWindow(OkHttpChannelBuilder.DEFAULT_FLOW_CONTROL_WINDOW * 2)
```
The issue is not happens anymore.
Hope it will help someone.
